name: Shared Library

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - SharedLibrary/**
  pull_request:
    branches: [ "main" ]
    paths:
      - SharedLibrary/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: ${{ matrix.node-version }}

    - name: Setup
      working-directory: ./SharedLibrary
      run: |
        yarn install --frozen-lockfile
  
    - name: Lint
      working-directory: ./SharedLibrary
      run: |
        yarn lint

    - name: Test
      working-directory: ./SharedLibrary
      run: |
        yarn test
